# Generated by Django 4.2.7 on 2025-11-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='gametable',
            name='current_turn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gametable',
            name='discard_pile_json',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gametable',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='player',
            name='has_drawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
