# Generated by Django 4.2.7 on 2025-11-21 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rummy', '0002_alter_player_options_gametable_current_turn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='wild_joker',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
