# Generated by Django 4.2.7 on 2025-11-22 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rummy', '0003_gametable_wild_joker'),
    ]

    operations = [
        migrations.AddField(
            model_name='gametable',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_games', to='rummy.player'),
        ),
    ]
